import CardComponents from "@/components/CardComponents";
import DataTable from "@/components/TableView/data-table";

import { columns } from "@/components/TableView/columns";
const stats = [
  {
    title: "Total Organizations",
    amount: "1,234",
    description: "Total number of organizations registered in the system.",
    trendingDescription: "Trending Up",
  },
  {
    title: "Active Organizations",
    amount: "1,000",
    description: "Number of organizations currently active.",
    trendingDescription: "Trending Up",
  },
  {
    title: "Payment Due Organizations",
    amount: "234",
    description: "Number of organizations that are due for payment.",
    trendingDescription: "Trending Down",
  },
  {
    title: "New Organizations",
    amount: "50",
    description: "Number of new organizations registered this month.",
    trendingDescription: "Trending Up",
  },
];

// Table data
const tableData = [
  {
    id: "1",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "2",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Pending",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "4",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "5",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "6",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "7",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "8",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "9",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "10",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "11",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "12",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "13",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "14",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "15",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "16",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "17",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "18",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "19",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "20",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "21",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "22",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "23",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "24",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "25",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "26",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "27",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "28",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "29",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "30",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "31",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "32",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "33",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "34",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "35",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "36",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "37",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "38",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "39",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "40",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "41",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "42",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "43",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "44",
    name: "Rahat",
    parent: "N/A",
    subdomain: "rahatsubdomain",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-10-01",
    createdBy: "Admin",
    amount: 100,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
  {
    id: "45",
    name: "John Doe",
    parent: "N/A",
    subdomain: "johndoe",
    organizationType: "Type B",
    status: "Suspended",
    createdAt: "2023-09-15",
    createdBy: "Admin",
    amount: 200,
    billingCycle: "Yearly",
    paymentStatus: "Pending",
  },
  {
    id: "46",
    name: "Jane Smith",
    parent: "Rahat",
    subdomain: "janesmith",
    organizationType: "Type A",
    status: "Active",
    createdAt: "2023-08-20",
    createdBy: "Admin",
    amount: 300,
    billingCycle: "Monthly",
    paymentStatus: "Paid",
  },
];

const Organizations = () => {
  return (
    <div className="container mx-auto p-2">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3 lg:grid-cols-4">
        {stats.map((stat) => (
          <CardComponents key={stat.title} {...stat} />
        ))}
      </div>

      <div className="mt-4">
        <h2 className="text-2xl font-bold mb-4">Organizations List</h2>
        <DataTable columns={columns} data={tableData} />
      </div>
    </div>
  );
};

export default Organizations;
